In [1]:
# Rode uma única vez, se necessário:
# !pip install imbalanced-learn xgboost lightgbm ydata-profiling

In [2]:
# ============================================================================
# CLASSIFICAÇÃO COM BASE DESBALANCEADA — DATASET REAL (Fraudes de Cartão)
# EDA → Estratégias de Balanceamento → Comparação de Modelos
# ============================================================================
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold
from sklearn.metrics import (accuracy_score, precision_score, recall_score, f1_score,
                             roc_auc_score, confusion_matrix, average_precision_score)
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

# Balanceamento (imbalanced-learn)
from imblearn.under_sampling import RandomUnderSampler, NearMiss
from imblearn.over_sampling import RandomOverSampler, SMOTE, ADASYN, BorderlineSMOTE
from imblearn.combine import SMOTEENN, SMOTETomek
from imblearn.ensemble import BalancedRandomForestClassifier

# Modelos avançados
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier

# EDA
from ydata_profiling import ProfileReport

import warnings
warnings.filterwarnings('ignore')

print("Imports OK ✅")

Imports OK ✅

C:\Users\calab\AppData\Local\Temp\ipykernel_13616\3498552584.py:29: DeprecationWarning:
    `import ydata_profiling` is deprecated and will not receive more updates.
    Please install fg-data-profiling via `pip install fg-data-profiling` and use `import data_profiling` instead.

  from ydata_profiling import ProfileReport

In [3]:
# ============================================================================
# DATASET REAL: Credit Card Fraud Detection (Kaggle — mlg-ulb)
# 284.807 transações, 492 fraudes (0,17%) — desbalanceamento EXTREMO 1:578
# ============================================================================
import os

caminho = '../datasets/creditcard.csv'

# Verifica se o arquivo existe; se não, tenta alternativas comuns
if not os.path.exists(caminho):
    alternativas = ['creditcard.csv', '../datasets/credit_card.csv', 'datasets/creditcard.csv']
    for alt in alternativas:
        if os.path.exists(alt):
            caminho = alt
            break

df = pd.read_csv(caminho)
print(f"Arquivo carregado: {caminho}")
print(df.info())

# Variável alvo: 'Class' (0 = transação normal, 1 = fraude)
print("\nDistribuição das classes:")
print(df['Class'].value_counts())

n_fraudes = (df['Class'] == 1).sum()
n_normais = (df['Class'] == 0).sum()
print(f"\n% de fraudes: {n_fraudes / len(df) * 100:.4f}%")
print(f"Razão de desbalanceamento: 1 : {n_normais // n_fraudes}")
print("→ Para cada 1 fraude, existem", f"{n_normais // n_fraudes}", "transações normais.")

Arquivo carregado: ../datasets/creditcard.csv
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB
None

Distribuição das classes:
Class
0    284315
1       492
Name: count, dtype: int64

% de fraudes: 0.1727%
Razão de desbalanceamento: 1 : 577
→ Para cada 1 fraude, existem 577 transações normais.

In [4]:
# ============================================================================
# EDA AUTOMÁTICA — ydata_profiling
# Gera um relatório HTML interativo completo (distribuições, correlações, nulos)
# ============================================================================
# ⚠️ Roda no dataset COMPLETO (284k linhas) pode levar alguns minutos.
# Para agilizar, use uma amostra estratificada (mantém a proporção das classes):
amostra_eda = df.groupby('Class', group_keys=False).apply(
    lambda x: x.sample(min(len(x), 20000), random_state=42)
)

profile = ProfileReport(amostra_eda, title="EDA — Fraudes de Cartão (Desbalanceado)",
                        explorative=True)
profile.to_file("../outputs/eda_fraudes.html")      # salva o HTML na pasta do notebook
# profile.to_notebook_iframe()           # ou exiba inline no Jupyter
print("Relatório gerado: eda_fraudes.html (abra no navegador)")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/31 [00:00<?, ?it/s]
 32%|███▏      | 10/31 [00:00<00:00, 95.66it/s]
 65%|██████▍   | 20/31 [00:00<00:00, 62.09it/s]
100%|██████████| 31/31 [00:00<00:00, 68.01it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

Relatório gerado: eda_fraudes.html (abra no navegador)

In [5]:
# ============================================================================
# EDA MANUAL — visualizações essenciais do desbalanceamento
# ============================================================================
fig, axes = plt.subplots(1, 3, figsize=(18, 5))

# 1. Distribuição das classes
sns.countplot(x='Class', data=df, ax=axes[0], palette=['#4C72B0', '#C44E52'])
axes[0].set_title('Distribuição das Classes\n(0 = normal, 1 = fraude)')
axes[0].set_xticklabels([f'Normal (99,83%)', f'Fraude (0,17%)'])

# 2. Boxplot de uma feature PCA por classe (V1)
sns.boxplot(x='Class', y='V1', data=df, ax=axes[1], palette=['#4C72B0', '#C44E52'])
axes[1].set_title('Feature V1 por Classe\n(separabilidade parcial)')

# 3. Valor da transação por classe (Amount NÃO é PCA — precisa escalar)
sns.boxplot(x='Class', y='Amount', data=df, ax=axes[2], palette=['#4C72B0', '#C44E52'])
axes[2].set_title('Valor da Transação (Amount) por Classe')
axes[2].set_yscale('log')

plt.tight_layout()
plt.show()

# Diagnóstico numérico
print(f"Razão de desbalanceamento: 1 : {n_normais // n_fraudes}")
print("→ A classe minoritária (fraude) é o que queremos DETECTAR.")
print("→ Acurácia será enganosa: prever 'tudo normal' acerta 99,83%.")

Razão de desbalanceamento: 1 : 577
→ A classe minoritária (fraude) é o que queremos DETECTAR.
→ Acurácia será enganosa: prever 'tudo normal' acerta 99,83%.

In [6]:
# ============================================================================
# O PROBLEMA CENTRAL: POR QUE A ACURÁCIA ENGANAR NESTE DATASET
# ============================================================================
# Um modelo "burro" que prevê TUDO como normal acerta 99,83% das vezes.
# Mas ele NÃO detecta NENHUMA fraude — recall = 0!

y_burro = np.zeros_like(df['Class'].values)   # prevê sempre classe 0 (normal)

acc_burro = accuracy_score(df['Class'], y_burro)
rec_burro = recall_score(df['Class'], y_burro)

print(f"Acurácia do modelo 'chuta tudo normal': {acc_burro:.4f} ({acc_burro*100:.2f}%)")
print(f"Recall da classe fraude: {rec_burro:.4f} ← ZERO!")
print(f"\n→ Parece excelente (99,83%), mas o modelo é INÚTIL:")
print(f"→ Ele deixaria passar TODAS as 492 fraudes sem nenhum alerta!")
print("\nMoral: em base desbalanceada, use PRECISION, RECALL, F1 e PR-AUC.")
print("O próprio dataset recomenda PR-AUC (Area Under Precision-Recall Curve).")

Acurácia do modelo 'chuta tudo normal': 0.9983 (99.83%)
Recall da classe fraude: 0.0000 ← ZERO!

→ Parece excelente (99,83%), mas o modelo é INÚTIL:
→ Ele deixaria passar TODAS as 492 fraudes sem nenhum alerta!

Moral: em base desbalanceada, use PRECISION, RECALL, F1 e PR-AUC.
O próprio dataset recomenda PR-AUC (Area Under Precision-Recall Curve).

In [7]:
# ============================================================================
# FUNÇÃO DE AVALIAÇÃO — validação cruzada ESTRATIFICADA
# ============================================================================
# StratifiedKFold garante que cada fold preserve a proporção 99,83/0,17.
# Sem isso, um fold poderia ficar sem NENHUMA fraude e quebrar as métricas.

def avaliar_modelo(modelo, X, y, nome, cv=5):
    """Avalia com CV estratificada e métricas corretas para dados desbalanceados."""
    skf = StratifiedKFold(n_splits=cv, shuffle=True, random_state=42)

    acc  = cross_val_score(modelo, X, y, cv=skf, scoring='accuracy').mean()
    prec = cross_val_score(modelo, X, y, cv=skf, scoring='precision').mean()
    rec  = cross_val_score(modelo, X, y, cv=skf, scoring='recall').mean()
    f1   = cross_val_score(modelo, X, y, cv=skf, scoring='f1').mean()
    roc  = cross_val_score(modelo, X, y, cv=skf, scoring='roc_auc').mean()

    print(f"{nome:38s} | Acc {acc:.3f} | Prec {prec:.3f} | Rec {rec:.3f} | F1 {f1:.3f} | AUC {roc:.3f}")
    return {'modelo': nome, 'accuracy': acc, 'precision': prec,
            'recall': rec, 'f1': f1, 'roc_auc': roc}

In [8]:
# ============================================================================
# PREPARAÇÃO DOS DADOS
# ============================================================================
# 1) AMOSTRAGEM ESTRATIFICADA: mantém TODAS as fraudes + 20.000 normais.
#    → Preserva o desbalanceamento real (~1:40) e reduz o tempo de execução.
# 2) SPLIT treino/teste ANTES de qualquer balanceamento (regra de ouro!).
#    → Nunca balanceie o dataset inteiro — vazamento de dados para o teste.

X = df.drop('Class', axis=1).values
y = df['Class'].values

# Amostra estratificada (todas as fraudes + 20k normais)
idx_fraude = np.where(y == 1)[0]
idx_normal = np.random.RandomState(42).choice(np.where(y == 0)[0], 20000, replace=False)
idx = np.concatenate([idx_fraude, idx_normal])

X_amostra, y_amostra = X[idx], y[idx]
print(f"Amostra: {len(y_amostra):,} linhas | "
      f"Fraudes: {(y_amostra==1).sum()} | "
      f"Proporção: {(y_amostra==1).mean()*100:.2f}%")

# Split estratificado (70% treino / 30% teste)
X_treino, X_teste, y_treino, y_teste = train_test_split(
    X_amostra, y_amostra, test_size=0.3, stratify=y_amostra, random_state=42
)

print(f"Treino: {X_treino.shape[0]:,} | Teste: {X_teste.shape[0]:,}")
print(f"Fraudes no treino: {(y_treino==1).sum()} | Fraudes no teste: {(y_teste==1).sum()}")

Amostra: 20,492 linhas | Fraudes: 492 | Proporção: 2.40%
Treino: 14,344 | Teste: 6,148
Fraudes no treino: 344 | Fraudes no teste: 148

#

# Técnicas de Balanceamento de Classes

## O problema

Quando uma classe domina os dados (ex.: 99% normal vs 1% fraude), o modelo
aprende só a classe majoritária e ignora a minoritária — justamente a que
mais importa. As técnicas abaixo reequilibram os dados (ou o modelo) para
resolver isso.

> **Regra de ouro:** balanceie **apenas o treino**. O teste mantém a
> proporção real.

---

## Os dados do exemplo

Vamos usar um dataset sintético com **10000 normais (0)** e **1000 fraudes (1)**:

In [9]:
import numpy as np
from collections import Counter

# Dados sintéticos: 10000 normais (0) e 1000 fraudes (1)
X = np.random.RandomState(42).randn(11000, 2)
y = np.array([0]*10000 + [1]*1000)

print("Antes:", Counter(y))

Antes: Counter({0: 10000, 1: 1000})

# Undersampling (Subamostragem)

## O que é

Undersampling é uma técnica de balanceamento de classes que atua **reduzindo a classe majoritária** — a classe com mais exemplos — para aproximá-la da quantidade da classe minoritária.

O objetivo é reequilibrar o dataset para que o modelo não "aprenda" apenas a classe dominante e passe a dar atenção também à classe rara (que costuma ser a mais importante, como fraude ou doença).

**Exemplo:** se temos 100 transações normais e 10 fraudes, o undersampling reduz os 100 normais para 10, deixando o dataset equilibrado em 10 e 10.

## Vantagem principal

- O dataset fica **menor**, então o treinamento fica **mais rápido**.

## Desvantagem principal

- **Descarta dados** da classe majoritária, o que pode significar **perda de informação** importante para o modelo.

---

## Formas de Undersampling

### 1. RandomUnderSampler

É a forma **mais simples** de undersampling.

**Como funciona:** remove exemplos da classe majoritária **de forma aleatória**, sem nenhum critério, até que a quantidade se iguale à da classe minoritária.

**Características:**

- Simples e rápido de aplicar
- Não analisa quais exemplos são mais ou menos importantes
- O risco é descartar exemplos valiosos por puro acaso

**Analogia:** é como jogar fora documentos de um arquivo sem olhar o conteúdo — alguns podem ser importantes.

---

### 2. NearMiss

É uma forma **mais inteligente** de undersampling.

**Como funciona:** em vez de remover aleatoriamente, o NearMiss **analisa a distância entre os exemplos** e mantém apenas os exemplos da classe majoritária que estão **mais próximos da classe minoritária**.

**Por que isso é bom:** os exemplos próximos da fronteira entre as classes são os **mais informativos** — são justamente os que ajudam o modelo a distinguir uma classe da outra.

**Características:**

- Preserva os exemplos mais úteis para a classificação
- Pode ser sensível a ruído e outliers nos dados
- Existem variações (versões 1, 2 e 3) que mudam o critério de distância usado

**Analogia:** em vez de jogar fora documentos aleatórios, você mantém apenas os que estão relacionados ao assunto que interessa.

---

## Comparação rápida

| Aspecto | RandomUnderSampler | NearMiss |
|---|---|---|
| Critério de remoção | Aleatório | Baseado em distância |
| Exemplos mantidos | Qualquer um | Os mais próximos da minoria |
| Complexidade | Baixa | Média |
| Risco principal | Perder dados importantes | Sensibilidade a ruído |
| Quando usar | Casos simples, dados grandes | Quando a fronteira entre classes importa |

---

## Resumo

O undersampling resolve o desbalanceamento **reduzindo a classe majoritária**. O **RandomUnderSampler** faz isso de forma aleatória e simples; o **NearMiss** faz isso de forma seletiva, mantendo os exemplos mais informativos. A escolha entre eles depende do equilíbrio entre **simplicidade** e **qualidade dos dados mantidos**.

In [10]:
from imblearn.under_sampling import RandomUnderSampler

# Aplica o undersampling aleatório
rus = RandomUnderSampler(random_state=42)
X_res, y_res = rus.fit_resample(X, y)

# Mostra o resultado
print("Antes: ", Counter(y))
print("Depois:", Counter(y_res))
print(f"Tamanho: {len(y)} → {len(y_res)} amostras")

Antes:  Counter({0: 10000, 1: 1000})
Depois: Counter({0: 1000, 1: 1000})
Tamanho: 11000 → 2000 amostras

In [11]:
from imblearn.under_sampling import NearMiss

# Aplica o undersampling seletivo (mantém normais próximos das fraudes)
nm = NearMiss(version=1)
X_res, y_res = nm.fit_resample(X, y)

# Mostra o resultado
print("Antes: ", Counter(y))
print("Depois:", Counter(y_res))
print(f"Tamanho: {len(y)} → {len(y_res)} amostras")

Antes:  Counter({0: 10000, 1: 1000})
Depois: Counter({0: 1000, 1: 1000})
Tamanho: 11000 → 2000 amostras

# Oversampling (Superamostragem)

## O que é

Oversampling é uma técnica de balanceamento de classes que atua **aumentando a classe minoritária** — ou seja, a classe que tem menos exemplos — para aproximá-la da quantidade da classe majoritária.

O objetivo é reequilibrar o dataset para que o modelo não "aprenda" apenas a classe dominante e passe a dar atenção também à classe rara (que costuma ser a mais importante, como fraude ou doença).

**Exemplo:** se temos 100 transações normais e 10 fraudes, o oversampling aumenta as 10 fraudes para 100, deixando o dataset equilibrado em 100 e 100.

## Vantagem principal

- **Nenhum dado é descartado** — toda a informação da classe majoritária é preservada.

## Desvantagem principal

- O dataset fica **maior**, o que pode **aumentar o tempo de treinamento** e o risco de **overfitting** (o modelo "decorar" os dados em vez de aprender padrões).

---

## Formas de Oversampling

### 1. RandomOverSampler

É a forma **mais simples** de oversampling.

**Como funciona:** duplica exemplos da classe minoritária **de forma aleatória**, com reposição, até que a quantidade se iguale à da classe majoritária.

**Características:**

- Simples e rápido de aplicar
- Não cria dados novos — apenas **cópias idênticas** dos exemplos existentes
- O risco principal é o **overfitting**: o modelo pode "decorar" as cópias repetidas em vez de aprender padrões gerais

**Analogia:** é como fotocopiar o mesmo documento várias vezes para encher uma pasta — o conteúdo continua sendo o mesmo, só que repetido.

---

## Resumo

O oversampling resolve o desbalanceamento **aumentando a classe minoritária**. O **RandomOverSampler** faz isso duplicando exemplos existentes de forma aleatória — simples e sem perder dados, mas com risco de overfitting por repetição. Existem formas mais avançadas (como o SMOTE, que cria exemplos sintéticos novos) que veremos em seguida.

In [12]:
from imblearn.over_sampling import RandomOverSampler

# Aplica o oversampling por duplicação aleatória
ros = RandomOverSampler(random_state=42)
X_res, y_res = ros.fit_resample(X, y)

# Mostra o resultado
print("Antes: ", Counter(y))
print("Depois:", Counter(y_res))
print(f"Tamanho: {len(y)} → {len(y_res)} amostras")

Antes:  Counter({0: 10000, 1: 1000})
Depois: Counter({0: 10000, 1: 10000})
Tamanho: 11000 → 20000 amostras

# SMOTE (Synthetic Minority Over-sampling TEchnique)

## O que é

SMOTE é uma técnica de **oversampling** que cria **exemplos sintéticos novos** para a classe minoritária, em vez de apenas duplicar os existentes.

Enquanto o RandomOverSampler copia exemplos idênticos (risco de overfitting), o SMOTE **inventa pontos plausíveis** entre os exemplos reais da minoria — o modelo aprende padrões mais gerais, não decora cópias.

**Exemplo:** se temos 100 transações normais e 10 fraudes, o SMOTE cria 90 fraudes sintéticas, deixando o dataset equilibrado em 100 e 100.

## Como funciona

1. Para cada exemplo da classe minoritária, encontra seus **k vizinhos mais próximos** (também da minoria)
2. Escolhe um vizinho aleatoriamente
3. Cria um novo ponto **sobre o segmento de reta** entre o exemplo original e o vizinho escolhido
4. Repete até equilibrar as classes

**Analogia:** é como um professor que, em vez de repetir o mesmo exercício, cria variações novas do exercício — mesmas ideias, mas combinações diferentes.

## Vantagens

- Gera dados **novos** (não duplica) — reduz o risco de overfitting
- Preserva toda a informação da classe majoritária (não descarta nada)
- É o **padrão-ouro** do oversampling — o mais usado na prática

## Desvantagens

- Pode criar exemplos **irreais** em regiões com ruído ou outliers
- Sensível ao parâmetro `k_neighbors` (número de vizinhos)
- Não funciona bem com dados de **alta dimensionalidade** (muitas features)
- Não suporta variáveis **categóricas** diretamente (precisa de variações)

---

## Variações do SMOTE

### 1. BorderlineSMOTE

**O que faz:** cria exemplos sintéticos **apenas na fronteira** entre as classes — onde a classificação é mais difícil e o modelo mais erra.

**Por que isso é bom:** focar na fronteira ajuda o modelo a "desenhar" melhor o limite entre as classes.

**Características:**

- Existem 2 versões (1 e 2) que variam o critério de seleção dos exemplos
- Pode amplificar ruído se a fronteira for muito bagunçada

**Analogia:** em vez de estudar o assunto todo, você revisa só os pontos onde costuma errar na prova.

---

### 2. ADASYN (Adaptive Synthetic Sampling)

**O que faz:** gera **mais exemplos sintéticos onde a minoria é mais difícil** de classificar (onde há mais vizinhos da classe majoritária ao redor) e menos onde ela já é bem representada.

**Por que isso é bom:** adapta o esforço de síntese à dificuldade local dos dados.

**Características:**

- A distribuição final **não fica exatamente 50/50** — varia conforme a dificuldade
- Muito sensível a ruído (pode gerar exemplos espúrios em regiões ruidosas)

**Analogia:** o professor dá mais exercícios sobre o assunto que a turma menos entendeu.

---

### 3. KMeansSMOTE

**O que faz:** primeiro agrupa os dados com **K-Means** (clusters) e depois aplica o SMOTE **dentro de cada cluster**, priorizando os clusters com mais exemplos da minoria.

**Por que isso é bom:** evita criar exemplos sintéticos em regiões vazias ou irreais — os novos pontos ficam em regiões densas e plausíveis.

**Características:**

- Mais robusto a dados com distribuições complexas
- Mais caro computacionalmente (roda K-Means antes)

**Analogia:** em vez de inventar exemplos em qualquer lugar, você só cria dentro de "bairros" que já existem nos dados.

---

### 4. SVM-SMOTE

**O que faz:** usa uma **SVM** (Support Vector Machine) para identificar os exemplos da minoria próximos da fronteira de decisão e aplica o SMOTE apenas nesses pontos.

**Por que isso é bom:** a SVM encontra a fronteira de forma mais precisa que a simples distância aos vizinhos.

**Características:**

- Bom quando a fronteira entre classes é complexa
- Mais lento (treina uma SVM antes)

---

### 5. SMOTE-NC (SMOTE Nominal Continuous)

**O que faz:** versão do SMOTE para dados que misturam **variáveis numéricas e categóricas** (ex.: sexo, cidade, tipo de contrato).

**Por que isso é bom:** o SMOTE tradicional não sabe interpolar entre categorias — o SMOTE-NC trata isso de forma adequada.

**Características:**

- Usado quando há colunas categóricas no dataset
- Para dados 100% categóricos, existe o SMOTE-N

---

## Comparação rápida

| Variação | Onde cria os exemplos | Quando usar |
|---|---|---|
| SMOTE (original) | Entre vizinhos da minoria | Padrão-ouro, comece por aqui |
| BorderlineSMOTE | Na fronteira entre classes | Fronteira difícil |
| ADASYN | Onde a minoria é mais difícil | Dificuldade varia no espaço |
| KMeansSMOTE | Dentro de clusters densos | Distribuição complexa |
| SVM-SMOTE | Próximo à fronteira da SVM | Fronteira complexa |
| SMOTE-NC | Com suporte a categóricas | Dados mistos (num + cat) |

---

## Resumo

O SMOTE resolve o desbalanceamento **criando exemplos sintéticos** da classe minoritária por interpolação entre vizinhos — mais robusto que a simples duplicação do RandomOverSampler. Suas variações mudam **onde** os exemplos são criados: na fronteira (BorderlineSMOTE, SVM-SMOTE), onde há mais dificuldade (ADASYN), dentro de clusters (KMeansSMOTE) ou com suporte a categóricas (SMOTE-NC). A regra prática: **comece com o SMOTE original** e teste variações se o problema tiver características específicas.

In [13]:
from imblearn.over_sampling import SMOTE

# Cria exemplos sintéticos interpolando entre vizinhos da minoria
smote = SMOTE(random_state=42)
X_res, y_res = smote.fit_resample(X, y)

print("Antes: ", Counter(y))
print("Depois:", Counter(y_res))
print(f"Tamanho: {len(y)} → {len(y_res)} amostras")

Antes:  Counter({0: 10000, 1: 1000})
Depois: Counter({0: 10000, 1: 10000})
Tamanho: 11000 → 20000 amostras

In [14]:
from imblearn.over_sampling import BorderlineSMOTE

# Cria exemplos sintéticos APENAS na fronteira entre as classes
bsmote = BorderlineSMOTE(random_state=42)
X_res, y_res = bsmote.fit_resample(X, y)

print("Antes: ", Counter(y))
print("Depois:", Counter(y_res))
print(f"Tamanho: {len(y)} → {len(y_res)} amostras")

Antes:  Counter({0: 10000, 1: 1000})
Depois: Counter({0: 10000, 1: 10000})
Tamanho: 11000 → 20000 amostras

In [15]:
from imblearn.over_sampling import ADASYN

# Cria MAIS exemplos onde a minoria é mais difícil de classificar
adasyn = ADASYN(random_state=42)
X_res, y_res = adasyn.fit_resample(X, y)

print("Antes: ", Counter(y))
print("Depois:", Counter(y_res))
print(f"Tamanho: {len(y)} → {len(y_res)} amostras")

Antes:  Counter({0: 10000, 1: 1000})
Depois: Counter({1: 10104, 0: 10000})
Tamanho: 11000 → 20104 amostras

In [16]:
from imblearn.over_sampling import KMeansSMOTE

try: 
    # Agrupa os dados em clusters e aplica SMOTE dentro de cada cluster
    kmeans_smote = KMeansSMOTE(random_state=42)
    X_res, y_res = kmeans_smote.fit_resample(X, y)
    
    print("Antes: ", Counter(y))
    print("Depois:", Counter(y_res))
    print(f"Tamanho: {len(y)} → {len(y_res)} amostras")
except Exception as e:
    print(e)

  File "C:\Users\calab\AppData\Local\Programs\Python\Python311\Lib\site-packages\joblib\externals\loky\backend\context.py", line 257, in _count_physical_cores
    cpu_info = subprocess.run(
               ^^^^^^^^^^^^^^^
  File "C:\Users\calab\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\calab\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\calab\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

No clusters found with sufficient samples of class 1. Try lowering the cluster_balance_threshold or increasing the number of clusters.

# Conheça seus dados antes de escolher a técnica

## Por que isso importa

Não existe "melhor técnica de balanceamento" — existe a **melhor técnica
para os seus dados**. Escolher o método sem antes analisar o dataset é
como receitar remédio sem examinar o paciente.

O erro que cometemos com o KMeansSMOTE é a prova viva disso: o código
estava correto, mas os dados não atendiam ao que a técnica exige. O
problema não era o algoritmo — era a **falta de conhecimento sobre os
dados** antes da escolha.

## O que você precisa saber sobre os dados

### 1. Qual é a proporção do desbalanceamento?

- Desbalanceamento **leve** (ex.: 2:1) → técnicas simples resolvem
- Desbalanceamento **severo** (ex.: 100:1) → técnicas mais robustas

**Exemplo da aula:** com 10 fraudes em 110 (9,09%), o KMeansSMOTE falhou
porque o limiar padrão de 10% de minoria por cluster era maior que a
proporção global. Se tivéssemos calculado a proporção **antes**, saberíamos
que precisaríamos ajustar o `cluster_balance_threshold`.

### 2. Quantos exemplos da minoria existem?

- **Muitos** (centenas/milhares) → quase todas as técnicas funcionam
- **Poucos** (menos de ~50) → técnicas sofisticadas (KMeansSMOTE,
  SVM-SMOTE) podem falhar; SMOTE e undersampling são mais seguros

### 3. Os dados têm ruído ou outliers?

- Dados **limpos** → SMOTE e variações funcionam bem
- Dados **ruidosos** → prefira métodos que limpam (SMOTEENN) ou que não
  criam dados (Class Weight)

### 4. Quantas features (dimensões) existem?

- **Poucas dimensões** → SMOTE interpola bem
- **Muitas dimensões** → a distância entre vizinhos perde significado
  ("maldição da dimensionalidade") — SMOTE pode criar exemplos irreais

### 5. As variáveis são numéricas, categóricas ou mistas?

- **Só numéricas** → qualquer técnica serve
- **Mistas (num + cat)** → SMOTE-NC ou codificação adequada
- **Só categóricas** → SMOTE-N

### 6. Como os dados estão distribuídos no espaço?

- Minoria **concentrada** em uma região → SMOTE simples resolve
- Minoria **espalhada** ou com regiões de dificuldade variada → ADASYN,
  KMeansSMOTE
- Fronteira **complexa** → BorderlineSMOTE, SVM-SMOTE

## As perguntas que você deve fazer antes de escolher

1. Qual a proporção entre as classes? (calcule com `Counter(y)`)
2. Quantos exemplos tem a classe minoritária?
3. Os dados têm ruído visível? Há outliers?
4. Quantas colunas (features) o dataset tem?
5. Há variáveis categóricas?
6. A minoria está concentrada ou espalhada?

## Checklist rápido

| Pergunta | O que ela decide |
|---|---|
| Proporção do desbalanceamento | Técnica simples vs. robusta |
| Quantidade de minoria | Se técnicas sofisticadas vão funcionar |
| Ruído / outliers | Se precisa de limpeza (SMOTEENN) |
| Dimensionalidade | Se SMOTE é viável |
| Tipos de variáveis | SMOTE-NC vs. SMOTE tradicional |
| Distribuição da minoria | Qual variação do SMOTE usar |

## A lição da aula

O erro do KMeansSMOTE não foi um bug — foi um **alerta didático**: se
tivéssemos olhado os dados primeiro (proporção de 9,09% vs. limiar de
10%), teríamos previsto a falha antes de rodar o código.

**Regra de ouro:** antes de qualquer técnica de balanceamento, explore os
dados. Calcule a proporção, conte os exemplos, olhe a distribuição. A
técnica certa é consequência do conhecimento dos dados — não o contrário.

In [17]:
from imblearn.over_sampling import SVMSMOTE

# Usa uma SVM para achar a fronteira e cria exemplos perto dela
svm_smote = SVMSMOTE(random_state=42)
X_res, y_res = svm_smote.fit_resample(X, y)

print("Antes: ", Counter(y))
print("Depois:", Counter(y_res))
print(f"Tamanho: {len(y)} → {len(y_res)} amostras")

Antes:  Counter({0: 10000, 1: 1000})
Depois: Counter({0: 10000, 1: 5950})
Tamanho: 11000 → 15950 amostras

In [18]:
from imblearn.over_sampling import SMOTENC

# SMOTE-NC precisa de uma coluna categórica — vamos criar uma
# (coluna 2 = categórica com valores 0, 1 ou 2)
X_cat = np.column_stack([X, np.random.RandomState(42).randint(0, 3, len(y))])

smotenc = SMOTENC(categorical_features=[2], random_state=42)
X_res, y_res = smotenc.fit_resample(X_cat, y)

print("Antes: ", Counter(y))
print("Depois:", Counter(y_res))
print(f"Tamanho: {len(y)} → {len(y_res)} amostras")

Antes:  Counter({0: 10000, 1: 1000})
Depois: Counter({0: 10000, 1: 10000})
Tamanho: 11000 → 20000 amostras

# SMOTEENN (SMOTE + Edited Nearest Neighbors)

## O que é

SMOTEENN é uma técnica **híbrida** de balanceamento que combina duas
estratégias em sequência: primeiro **cria** dados sintéticos (SMOTE) e
depois **limpa** os dados (Edited Nearest Neighbors).

A ideia é aproveitar o melhor dos dois mundos: o SMOTE aumenta a classe
minoritária com exemplos novos, e o ENN remove exemplos "ruidosos" ou
ambíguos que atrapalham a classificação.

**Exemplo:** se temos 100 transações normais e 10 fraudes, o SMOTE cria
fraudes sintéticas até equilibrar (100 e 100) e depois o ENN remove os
exemplos problemáticos que sobraram.

## Como funciona

### Etapa 1 — SMOTE (cria)

1. Para cada exemplo da classe minoritária, encontra seus **k vizinhos
   mais próximos**
2. Cria novos exemplos sintéticos interpolando entre o exemplo original
   e um vizinho escolhido
3. Repete até equilibrar as classes

### Etapa 2 — ENN (limpa)

1. Para **cada exemplo** do dataset (agora balanceado), verifica a classe
   dos seus **k vizinhos mais próximos**
2. Se a maioria dos vizinhos tem classe **diferente** da do exemplo, ele é
   considerado ruidoso/ambíguo e é **removido**
3. Isso vale para exemplos de **ambas as classes** — maioria e minoria

**Analogia:** é como um professor que primeiro cria exercícios novos para
a turma (SMOTE) e depois **corrige e descarta** as questões que estão
erradas ou confusas (ENN).

## Vantagens

- **Equilibra E limpa** — não só aumenta a minoria, mas remove ruído
- Reduz o risco de o modelo aprender com exemplos ambíguos da fronteira
- Costuma gerar datasets de **qualidade superior** ao SMOTE puro

## Desvantagens

- **Mais lento** — executa dois algoritmos em sequência
- Pode remover exemplos válidos da minoria (se estiverem "cercados" pela
  maioria)
- O resultado final **não é exatamente 50/50** — a contagem varia conforme
  o que o ENN remove

## SMOTETomek — a "prima" do SMOTEENN

Existe outra técnica híbrida muito parecida: o **SMOTETomek**, que troca
o ENN pelo **Tomek Links**.

| Aspecto | SMOTEENN | SMOTETomek |
|---|---|---|
| Etapa de criação | SMOTE | SMOTE |
| Etapa de limpeza | ENN (remove ruído) | Tomek Links (remove pares ambíguos) |
| Agressividade | Mais agressivo (remove mais) | Mais conservador (remove menos) |
| Resultado | Dataset menor e mais limpo | Dataset mais próximo do original |

**Tomek Links:** pares de exemplos de classes diferentes que são vizinhos
mais próximos entre si — pontos ambíguos da fronteira. O SMOTETomek
remove apenas esses pares, enquanto o ENN remove qualquer exemplo cercado
pela classe oposta.

## Comparação com as outras técnicas

| Técnica | O que faz | Resultado típico |
|---|---|---|
| RandomOverSampler | Duplica a minoria | 100 + 100 (cópias) |
| SMOTE | Cria minoria sintética | 100 + 100 (novos) |
| SMOTEENN | Cria minoria + limpa ruído | ~100 + ~90 (limpos) |
| SMOTETomek | Cria minoria + remove pares ambíguos | ~100 + ~95 (limpos) |

## Quando usar

- **Fronteira ruidosa** entre as classes (muitos exemplos ambíguos)
- Quando o SMOTE puro gera exemplos sintéticos "irreais" em regiões
  bagunçadas
- Quando o dataset é pequeno o suficiente para o custo extra de
  processamento não ser problema

## Resumo

O SMOTEENN é a técnica híbrida que **cria dados sintéticos (SMOTE) e
depois limpa o ruído (ENN)**. É mais robusto que o SMOTE puro em dados
ruidosos, porém mais lento e com resultado final que varia conforme a
limpeza. A escolha entre SMOTEENN e SMOTETomek depende de quão agressiva
a limpeza precisa ser.

In [19]:
from imblearn.combine import SMOTEENN

# Etapa 1: SMOTE cria fraudes sintéticas
# Etapa 2: ENN remove exemplos ruidosos (cercados pela classe oposta)
smeenn = SMOTEENN(random_state=42)
X_res, y_res = smeenn.fit_resample(X, y)

print("Antes: ", Counter(y))
print("Depois:", Counter(y_res))
print(f"Tamanho: {len(y)} → {len(y_res)} amostras")

Antes:  Counter({0: 10000, 1: 1000})
Depois: Counter({1: 5278, 0: 4880})
Tamanho: 11000 → 10158 amostras

In [20]:
from imblearn.combine import SMOTETomek

# Etapa 1: SMOTE cria fraudes sintéticas
# Etapa 2: Tomek Links remove pares de classes diferentes que são
#          vizinhos mais próximos entre si (pontos ambíguos da fronteira)
smtomek = SMOTETomek(random_state=42)
X_res, y_res = smtomek.fit_resample(X, y)

print("Antes: ", Counter(y))
print("Depois:", Counter(y_res))
print(f"Tamanho: {len(y)} → {len(y_res)} amostras")

Antes:  Counter({0: 10000, 1: 1000})
Depois: Counter({0: 8766, 1: 8766})
Tamanho: 11000 → 17532 amostras

# Técnicas de Reamostragem (Nível de Dados) — Resumo Geral

## O que são

São técnicas que **alteram o dataset antes do treinamento** para corrigir o
desbalanceamento entre classes. Diferente das técnicas de nível de
algoritmo (Class Weight, ensembles balanceados), elas devolvem um novo
conjunto de dados (`X_res, y_res`) com as classes equilibradas.

**Nota conceitual:** o termo "geração de dados" é usado de forma ampla —
o undersampling, na verdade, **remove** dados da maioria; o oversampling
**cria/duplica** dados da minoria; os híbridos **criam e limpam**.

---

## Família 1 — Undersampling (reduz a classe majoritária)

**Ideia:** remove exemplos da classe majoritária até igualar à minoria.

| Técnica | Como funciona | Resultado (10000 + 1000) |
|---|---|---|
| RandomUnderSampler | Remove normais aleatoriamente | 1000 + 1000 |
| NearMiss | Remove normais longe da fronteira | 1000 + 1000 |

**Vantagem:** dataset menor (treino mais rápido).
**Desvantagem:** perde informação da maioria — risco de underfitting.

---

## Família 2 — Oversampling (aumenta a classe minoritária)

**Ideia:** aumenta a minoria até igualar à maioria.

### 2.1 Duplicação

| Técnica | Como funciona | Resultado (10000 + 1000) |
|---|---|---|
| RandomOverSampler | Duplica fraudes aleatoriamente (cópias idênticas) | 10000 + 10000 |

**Vantagem:** simples, não perde dados.
**Desvantagem:** risco de overfitting (o modelo "decora" as cópias).

### 2.2 Criação sintética (SMOTE e variações)

**Ideia:** cria exemplos **novos e plausíveis** por interpolação entre
vizinhos da minoria — mais robusto que duplicar.

| Técnica | Onde cria os exemplos | Quando usar |
|---|---|---|
| SMOTE (original) | Entre vizinhos da minoria | Padrão-ouro, comece por aqui |
| BorderlineSMOTE | Na fronteira entre classes | Fronteira difícil |
| ADASYN | Onde a minoria é mais difícil | Dificuldade varia no espaço |
| KMeansSMOTE | Dentro de clusters densos | Distribuição complexa |
| SVM-SMOTE | Próximo à fronteira da SVM | Fronteira complexa |
| SMOTE-NC | Com suporte a categóricas | Dados mistos (num + cat) |

**Vantagem:** dados novos, menos overfitting que a duplicação.
**Desvantagem:** pode criar exemplos irreais em regiões ruidosas; técnicas
sofisticadas (KMeansSMOTE, SVM-SMOTE) exigem minoria suficiente para
funcionar.

---

## Família 3 — Híbridos (criam E limpam)

**Ideia:** combinam oversampling com limpeza de dados ambíguos/ruidosos.

| Técnica | Etapa de criação | Etapa de limpeza | Agressividade |
|---|---|---|---|
| SMOTEENN | SMOTE | ENN (remove ruído) | Mais agressivo |
| SMOTETomek | SMOTE | Tomek Links (remove pares ambíguos) | Mais conservador |

**Vantagem:** dataset final mais limpo — reduz o risco de aprender com
exemplos ambíguos da fronteira.
**Desvantagem:** mais lento (dois algoritmos em sequência); o resultado
final **não é exatamente 50/50** (a limpeza remove exemplos).

---

## Comparação geral

| Técnica | O que faz com os dados | Resultado (10000 + 1000) |
|---|---|---|
| RandomUnderSampler | Remove normais | 1000 + 1000 |
| NearMiss | Remove normais da fronteira | 1000 + 1000 |
| RandomOverSampler | Duplica fraudes | 10000 + 10000 (cópias) |
| SMOTE e variações | Cria fraudes sintéticas | 10000 + 10000 (novos) |
| SMOTEENN | Cria fraudes + limpa ruído | ~10000 + ~9000 (limpos) |
| SMOTETomek | Cria fraudes + remove pares ambíguos | ~10000 + ~9500 (limpos) |

---

## Regra prática de escolha

1. **Comece simples:** RandomUnderSampler ou RandomOverSampler como
   baseline rápido.
2. **Padrão-ouro:** SMOTE — funciona bem na maioria dos casos.
3. **Fronteira difícil:** BorderlineSMOTE ou SVM-SMOTE.
4. **Dados com regiões vazias:** KMeansSMOTE (cuidado: exige minoria
   suficiente — lembre do erro do `cluster_balance_threshold`).
5. **Colunas categóricas:** SMOTE-NC.
6. **Dados ruidosos:** SMOTEENN ou SMOTETomek (limpam o que criam).
7. **Sempre antes de escolher:** conheça seus dados — proporção do
   desbalanceamento, quantidade de minoria, ruído, dimensionalidade e
   tipos de variáveis.

---

## Resumo

As técnicas de reamostragem atuam **no nível dos dados**, produzindo um
dataset balanceado antes do treino. Dividem-se em três famílias:
**undersampling** (remove da maioria), **oversampling** (aumenta a minoria
— por duplicação ou criação sintética com SMOTE e variações) e
**híbridos** (criam e limpam, como SMOTEENN e SMOTETomek). A escolha
depende das características dos dados — não existe técnica universalmente
melhor.

# Class Weight (Peso das Classes)

## O que é

Class Weight é uma técnica de balanceamento que **não altera os dados** —
nem cria, nem remove, nem duplica exemplos. Em vez disso, ela diz ao
modelo: *"errar na classe minoritária custa mais caro do que errar na
majoritária"*.

O modelo passa a "se esforçar" mais para acertar a classe rara (que
costuma ser a mais importante, como fraude ou doença), porque o erro nela
tem um peso maior na função de custo.

**Exemplo:** se temos 100 transações normais e 10 fraudes, o Class Weight
atribui um peso 10× maior para cada fraude. O dataset continua com 110
amostras — nada muda nos dados, muda apenas a importância de cada erro.

## Como funciona

1. Calcula-se um **peso para cada classe**, inversamente proporcional à
   sua frequência (método `balanced`)
2. O peso é passado ao modelo (ex.: `class_weight='balanced'` no
   scikit-learn)
3. Durante o treinamento, o erro cometido em um exemplo da classe
   minoritária é **multiplicado pelo peso** daquela classe
4. O modelo aprende a minimizar o erro **ponderado** — e passa a priorizar
   acertos na minoria

**Fórmula do peso (método balanced):**

$$w_j = \frac{n}{k \cdot n_j}$$

em que:

n = número total de amostras    
k = número de classes   
n_j = número de amostras da classe j   

**Analogia:** é como um professor que dá **peso maior** para as questões
mais difíceis na prova — a nota final reflete mais o desempenho nelas, sem
mudar o conteúdo da prova.

## Vantagens

- **Custo zero de dados** — não cria, não remove, não duplica nada
- **Sem risco de overfitting** por duplicação (diferente do
  RandomOverSampler)
- **Sem risco de perda de informação** (diferente do undersampling)
- **Simples de aplicar** — um único parâmetro no modelo
- Funciona bem com **qualquer quantidade de minoria**, até com pouquíssimos
  exemplos

## Desvantagens

- **Não adiciona informação nova** — o modelo só tem os dados que já
  existiam
- Em desbalanceamentos **muito severos**, o peso pode ficar extremo e
  desestabilizar o treinamento
- O efeito depende do **algoritmo** — nem todos os modelos suportam
  `class_weight` (árvores, regressão logística e SVM suportam; redes
  neurais precisam de ajuste manual na função de perda)

## Quando usar

- **Sempre que quiser começar** — é a técnica mais barata e segura
- Quando o dataset é **pequeno** e não se pode descartar dados
- Quando há **pouquíssimos exemplos** da minoria (técnicas como
  KMeansSMOTE falham, mas Class Weight funciona)
- Como **baseline** para comparar com as outras técnicas

## Resumo

O Class Weight resolve o desbalanceamento **sem tocar nos dados** — apenas
pondera o erro do modelo a favor da classe minoritária. É a técnica mais
simples, barata e segura, ideal como ponto de partida. Sua principal
limitação é não adicionar informação nova, o que pode ser insuficiente em
casos muito severos — aí vale combinar com outras técnicas ou usar
ensemble balanceado.

# Ensemble Balanceado (Balanced Ensemble)

## O que é

Ensemble balanceado é uma abordagem de balanceamento que **não altera os
dados** — nem cria, nem remove, nem duplica exemplos. Em vez disso, o
**próprio algoritmo** resolve o desbalanceamento internamente, treinando
cada modelo do conjunto (ensemble) em um **subconjunto balanceado** dos
dados.

A ideia é combinar o poder dos ensembles (vários modelos votando) com o
balanceamento automático: cada árvore/estimador enxerga uma versão
equilibrada do dataset, e a decisão final é a agregação de todos.

**Exemplo:** se temos 10000 normais e 1000 fraudes, o ensemble balanceado
não mexe no dataset — cada árvore treina em um subconjunto com proporção
equilibrada (ex.: 1000 + 1000) sorteado dos dados originais.

## Como funciona (ideia geral)

1. Para **cada modelo** do ensemble, sorteia-se um subconjunto dos dados
   com as classes **balanceadas** (geralmente por undersampling aleatório
   da maioria)
2. Cada modelo treina no seu subconjunto balanceado
3. A previsão final é a **agregação** (votação ou média) de todos os
   modelos

**Analogia:** é como uma banca de avaliação em que cada examinador recebe
uma prova com o mesmo número de questões fáceis e difíceis — a nota final
é a média da banca, e nenhuma questão original foi alterada.

## Vantagens

- **Não perde dados** (diferente do undersampling puro) — cada modelo usa
  uma amostra diferente da maioria, então no conjunto toda a informação é
  aproveitada
- **Não cria dados sintéticos** (diferente do SMOTE) — sem risco de
  exemplos irreais
- **Sem overfitting por duplicação** (diferente do RandomOverSampler)
- Combina o balanceamento com a robustez natural dos ensembles

## Desvantagens

- **Mais custoso computacionalmente** — treina vários modelos em vez de um
- Mais complexo de explicar e interpretar
- O ganho depende do número de estimadores (mais estimadores = melhor,
  porém mais lento)

---

## Formas de fazer

### 1. BalancedRandomForest

**O que é:** uma Floresta Aleatória em que **cada árvore** treina em um
subconjunto balanceado dos dados (amostragem com reposição equilibrada).

**Como funciona:**

1. Para cada árvore, sorteia-se um bootstrap **balanceado** (mesma
   quantidade de maioria e minoria)
2. A árvore treina normalmente nesse subconjunto
3. A floresta combina as previsões de todas as árvores

**Características:**

- É o ensemble balanceado **mais usado** na prática
- Mantém a robustez da Floresta Aleatória contra overfitting
- Funciona bem com dados tabulares

---

### 2. BalancedBagging

**O que é:** a versão balanceada do **Bagging** (Bootstrap Aggregating) —
o mesmo princípio do BalancedRandomForest, mas com **qualquer estimador
base** (árvore, regressão logística, SVM, etc.), não só árvores.

**Como funciona:**

1. Para cada estimador, sorteia-se um subconjunto balanceado dos dados
2. Cada estimador treina no seu subconjunto
3. A previsão final é a agregação (votação para classificação)

**Características:**

- Mais flexível que o BalancedRandomForest (escolhe o estimador base)
- Permite testar diferentes algoritmos com balanceamento interno

---

### 3. EasyEnsemble

**O que é:** combina **vários subconjuntos balanceados** com **AdaBoost**.

**Como funciona:**

1. Divide a classe majoritária em **vários subconjuntos** (cada um com o
   mesmo tamanho da minoria)
2. Para cada subconjunto, treina um **AdaBoost** (majoritário + minoria)
3. A previsão final é a **média das probabilidades** de todos os AdaBoosts

**Características:**

- Cada AdaBoost é um ensemble em si (combina vários classificadores fracos)
- Bom para dados grandes — cada submodelo é pequeno e rápido

---

### 4. RUSBoost

**O que é:** combina **Random Under Sampling (RUS)** com **Boosting**
(AdaBoost).

**Como funciona:**

1. A cada iteração do boosting, sorteia-se um subconjunto com a maioria
   **reduzida aleatoriamente** (RUS)
2. O classificador fraco treina nesse subconjunto balanceado
3. O boosting ajusta os pesos dos exemplos errados e repete

**Características:**

- Muito eficiente em desbalanceamentos **severos**
- O undersampling aleatório a cada iteração traz variedade aos submodelos
- Mais rápido que EasyEnsemble em muitos casos

---

## Comparação rápida

| Forma | Estimador base | Balanceamento interno | Quando usar |
|---|---|---|---|
| BalancedRandomForest | Árvores | Bootstrap balanceado | Padrão-ouro, dados tabulares |
| BalancedBagging | Qualquer um | Bootstrap balanceado | Quer testar outros algoritmos |
| EasyEnsemble | AdaBoost | Vários subconjuntos | Dados grandes, severo |
| RUSBoost | AdaBoost + RUS | Undersampling a cada iteração | Desbalanceamento severo |

## Quando usar

- Quando **não se quer mexer nos dados** (nem criar, nem remover)
- Quando o dataset é **grande** e o custo extra de treinar vários modelos
  é aceitável
- Quando técnicas de reamostragem (SMOTE, undersampling) não trouxeram
  ganho
- Como alternativa robusta ao Class Weight quando o modelo simples não é
  suficiente

## Resumo

O ensemble balanceado resolve o desbalanceamento **dentro do algoritmo**:
cada modelo do conjunto treina em um subconjunto balanceado, e a decisão
final é a agregação de todos. As principais formas são o
**BalancedRandomForest** (padrão-ouro), o **BalancedBagging** (flexível),
o **EasyEnsemble** (vários AdaBoosts) e o **RUSBoost** (boosting com
undersampling). É a técnica que combina robustez de ensemble com
balanceamento automático — sem tocar nos dados originais.

In [21]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

from imblearn.over_sampling import (RandomOverSampler, SMOTE, BorderlineSMOTE,
                                    ADASYN, KMeansSMOTE, SVMSMOTE)
from imblearn.under_sampling import RandomUnderSampler, NearMiss
from imblearn.combine import SMOTEENN, SMOTETomek

# 5 modelos de classificação padrão
modelos = {
    'Logística': LogisticRegression(max_iter=1000),
    'Árvore':    DecisionTreeClassifier(random_state=42),
    'Floresta':  RandomForestClassifier(n_estimators=100, random_state=42),
    'KNN':       KNeighborsClassifier(),
    'SVM':       SVC(),   # o mais lento — se demorar muito, troque por LinearSVC()
}

# Todas as técnicas de reamostragem (nível de dados)
tecnicas = {
    'Sem balanceamento':  None,
    'RandomUnderSampler': RandomUnderSampler(random_state=42),
    'NearMiss':           NearMiss(),
    'RandomOverSampler':  RandomOverSampler(random_state=42),
    'SMOTE':              SMOTE(random_state=42),
    'BorderlineSMOTE':    BorderlineSMOTE(random_state=42),
    'ADASYN':             ADASYN(random_state=42),
    'KMeansSMOTE':        KMeansSMOTE(cluster_balance_threshold=0.01, random_state=42),
    'SVMSMOTE':           SVMSMOTE(random_state=42),
    'SMOTEENN':           SMOTEENN(random_state=42),
    'SMOTETomek':         SMOTETomek(random_state=42),
}

In [22]:
from sklearn.metrics import recall_score, precision_score, f1_score, accuracy_score

resultados = []

for nome_tec, tec in tecnicas.items():
    # Aplica a reamostragem SÓ no treino
    if tec is None:
        X_treino_bal, y_treino_bal = X_treino, y_treino
    else:
        X_treino_bal, y_treino_bal = tec.fit_resample(X_treino, y_treino)

    for nome_mod, modelo in modelos.items():
        modelo.fit(X_treino_bal, y_treino_bal)
        y_pred = modelo.predict(X_teste)

        resultados.append({
            'Técnica':  nome_tec,
            'Modelo':   nome_mod,
            'Recall':   recall_score(y_teste, y_pred),
            'Precisão': precision_score(y_teste, y_pred),
            'F1':       f1_score(y_teste, y_pred),
            'Acurácia': accuracy_score(y_teste, y_pred),
        })

df_reamostragem = pd.DataFrame(resultados)
df_reamostragem

               Técnica     Modelo    Recall  Precisão        F1  Acurácia
0    Sem balanceamento  Logística  0.844595  0.984252  0.909091  0.995934
1    Sem balanceamento     Árvore  0.858108  0.858108  0.858108  0.993169
2    Sem balanceamento   Floresta  0.851351  0.984375  0.913043  0.996096
3    Sem balanceamento        KNN  0.114865  0.680000  0.196532  0.977391
4    Sem balanceamento        SVM  0.000000  0.000000  0.000000  0.975927
5   RandomUnderSampler  Logística  0.925676  0.339109  0.496377  0.954782
6   RandomUnderSampler     Árvore  0.918919  0.180611  0.301887  0.897690
7   RandomUnderSampler   Floresta  0.898649  0.511538  0.651961  0.976903
8   RandomUnderSampler        KNN  0.682432  0.041874  0.078906  0.616461
9   RandomUnderSampler        SVM  0.533784  0.027450  0.052214  0.533507
10            NearMiss  Logística  0.918919  0.196816  0.324195  0.907775
11            NearMiss     Árvore  0.925676  0.081017  0.148994  0.745446
12            NearMiss   Floresta  0.932432  0.175127  0.294872  0.892648
13            NearMiss        KNN  0.750000  0.022533  0.043752  0.210800
14            NearMiss        SVM  0.432432  0.025620  0.048375  0.590436
15   RandomOverSampler  Logística  0.918919  0.441558  0.596491  0.970072
16   RandomOverSampler     Árvore  0.837838  0.855172  0.846416  0.992681
17   RandomOverSampler   Floresta  0.858108  0.984496  0.916968  0.996259
18   RandomOverSampler        KNN  0.351351  0.170492  0.229581  0.943234
19   RandomOverSampler        SVM  0.290541  0.027406  0.050087  0.734710
20               SMOTE  Logística  0.905405  0.644231  0.752809  0.985686
21               SMOTE     Árvore  0.837838  0.666667  0.742515  0.986012
22               SMOTE   Floresta  0.878378  0.948905  0.912281  0.995934
23               SMOTE        KNN  0.574324  0.075690  0.133753  0.820917
24               SMOTE        SVM  0.290541  0.027061  0.049511  0.731457
25     BorderlineSMOTE  Logística  0.905405  0.644231  0.752809  0.985686
26     BorderlineSMOTE     Árvore  0.864865  0.727273  0.790123  0.988939
27     BorderlineSMOTE   Floresta  0.871622  0.969925  0.918149  0.996259
28     BorderlineSMOTE        KNN  0.391892  0.093851  0.151436  0.894275
29     BorderlineSMOTE        SVM  0.263514  0.028761  0.051862  0.768055
30              ADASYN  Logística  0.898649  0.639423  0.747191  0.985361
31              ADASYN     Árvore  0.844595  0.668449  0.746269  0.986174
32              ADASYN   Floresta  0.878378  0.942029  0.909091  0.995771
33              ADASYN        KNN  0.587838  0.071487  0.127473  0.806278
34              ADASYN        SVM  0.290541  0.027423  0.050117  0.734873
35         KMeansSMOTE  Logística  0.891892  0.676923  0.769679  0.987150
36         KMeansSMOTE     Árvore  0.824324  0.787097  0.805281  0.990403
37         KMeansSMOTE   Floresta  0.858108  0.969466  0.910394  0.995934
38         KMeansSMOTE        KNN  0.209459  0.103333  0.138393  0.937215
39         KMeansSMOTE        SVM  0.222973  0.025346  0.045517  0.774886
40            SVMSMOTE  Logística  0.891892  0.758621  0.819876  0.990566
41            SVMSMOTE     Árvore  0.851351  0.759036  0.802548  0.989915
42            SVMSMOTE   Floresta  0.871622  0.977273  0.921429  0.996422
43            SVMSMOTE        KNN  0.364865  0.119469  0.180000  0.919974
44            SVMSMOTE        SVM  0.378378  0.031496  0.058152  0.704945
45            SMOTEENN  Logística  0.898649  0.671717  0.768786  0.986988
46            SMOTEENN     Árvore  0.858108  0.622549  0.721591  0.984060
47            SMOTEENN   Floresta  0.878378  0.935252  0.905923  0.995608
48            SMOTEENN        KNN  0.581081  0.064371  0.115903  0.786597
49            SMOTEENN        SVM  0.527027  0.027947  0.053079  0.547332
50          SMOTETomek  Logística  0.905405  0.600897  0.722372  0.983247
51          SMOTETomek     Árvore  0.858108  0.631841  0.727794  0.984548
52          SMOTETomek   Floresta  0.871622  0.934783  0.902098  0.995446
53          SMOTETomek        KNN  0.567568  0.075540  0.133333  0.822381
54          SMOTETomek        SVM  0.290541  0.027284  0.049884  0.733572

In [23]:
from imblearn.ensemble import (BalancedRandomForestClassifier,
                               BalancedBaggingClassifier,
                               EasyEnsembleClassifier,
                               RUSBoostClassifier)

# Class Weight nos modelos que suportam (KNN não suporta)
modelos_cw = {
    'Logística (CW)': LogisticRegression(class_weight='balanced', max_iter=1000),
    'Árvore (CW)':    DecisionTreeClassifier(class_weight='balanced', random_state=42),
    'Floresta (CW)':  RandomForestClassifier(class_weight='balanced', n_estimators=100, random_state=42),
    'SVM (CW)':       SVC(class_weight='balanced'),
}

# Ensembles balanceados (treinam direto nos dados originais)
ensembles = {
    'BalancedRandomForest': BalancedRandomForestClassifier(n_estimators=100, random_state=42),
    'BalancedBagging':      BalancedBaggingClassifier(n_estimators=100, random_state=42),
    'EasyEnsemble':         EasyEnsembleClassifier(n_estimators=10, random_state=42),
    'RUSBoost':             RUSBoostClassifier(n_estimators=50, random_state=42),
}

resultados_algo = []

for nome_mod, modelo in {**modelos_cw, **ensembles}.items():
    # Treina direto nos dados ORIGINAIS (sem fit_resample)
    modelo.fit(X_treino, y_treino)
    y_pred = modelo.predict(X_teste)

    resultados_algo.append({
        'Técnica':  'Nível de algoritmo',
        'Modelo':   nome_mod,
        'Recall':   recall_score(y_teste, y_pred),
        'Precisão': precision_score(y_teste, y_pred),
        'F1':       f1_score(y_teste, y_pred),
        'Acurácia': accuracy_score(y_teste, y_pred),
    })

df_algoritmo = pd.DataFrame(resultados_algo)
df_algoritmo

,Técnica,Modelo,Recall,Precisão,F1,Acurácia
0,Nível de algoritmo,Logística (CW),0.918919,0.470588,0.622426,0.973162
1,Nível de algoritmo,Árvore (CW),0.831081,0.866197,0.848276,0.992843
2,Nível de algoritmo,Floresta (CW),0.844595,0.984252,0.909091,0.995934
3,Nível de algoritmo,SVM (CW),0.371622,0.030387,0.056180,0.699414
4,Nível de algoritmo,BalancedRandomForest,0.891892,0.673469,0.767442,0.986988
5,Nível de algoritmo,BalancedBagging,0.898649,0.529880,0.666667,0.978367
6,Nível de algoritmo,EasyEnsemble,0.912162,0.448505,0.601336,0.970885
7,Nível de algoritmo,RUSBoost,0.871622,0.398148,0.546610,0.965192

In [24]:
# Junta tudo
df_final = pd.concat([df_reamostragem, df_algoritmo], ignore_index=True)

# Pivot: linhas = técnica, colunas = modelo, valores = Recall
pivot_recall = df_final.pivot_table(index='Técnica', columns='Modelo', values='Recall')
pivot_recall

Modelo,BalancedBagging,BalancedRandomForest,EasyEnsemble,Floresta,Floresta (CW),KNN,Logística,Logística (CW),RUSBoost,SVM,SVM (CW),Árvore,Árvore (CW)
Técnica,,,,,,,,,,,,,
ADASYN,NaN,NaN,NaN,0.878378,NaN,0.587838,0.898649,NaN,NaN,0.290541,NaN,0.844595,NaN
BorderlineSMOTE,NaN,NaN,NaN,0.871622,NaN,0.391892,0.905405,NaN,NaN,0.263514,NaN,0.864865,NaN
KMeansSMOTE,NaN,NaN,NaN,0.858108,NaN,0.209459,0.891892,NaN,NaN,0.222973,NaN,0.824324,NaN
NearMiss,NaN,NaN,NaN,0.932432,NaN,0.750000,0.918919,NaN,NaN,0.432432,NaN,0.925676,NaN
Nível de algoritmo,0.898649,0.891892,0.912162,NaN,0.844595,NaN,NaN,0.918919,0.871622,NaN,0.371622,NaN,0.831081
RandomOverSampler,NaN,NaN,NaN,0.858108,NaN,0.351351,0.918919,NaN,NaN,0.290541,NaN,0.837838,NaN
RandomUnderSampler,NaN,NaN,NaN,0.898649,NaN,0.682432,0.925676,NaN,NaN,0.533784,NaN,0.918919,NaN
SMOTE,NaN,NaN,NaN,0.878378,NaN,0.574324,0.905405,NaN,NaN,0.290541,NaN,0.837838,NaN
SMOTEENN,NaN,NaN,NaN,0.878378,NaN,0.581081,0.898649,NaN,NaN,0.527027,NaN,0.858108,NaN
SMOTETomek,NaN,NaN,NaN,0.871622,NaN,0.567568,0.905405,NaN,NaN,0.290541,NaN,0.858108,NaN
SVMSMOTE,NaN,NaN,NaN,0.871622,NaN,0.364865,0.891892,NaN,NaN,0.378378,NaN,0.851351,NaN
Sem balanceamento,NaN,NaN,NaN,0.851351,NaN,0.114865,0.844595,NaN,NaN,0.000000,NaN,0.858108,NaN

# Interpretação dos Resultados — Experimento de Balanceamento

## Contexto do experimento

Rodamos 5 modelos de classificação (Logística, Árvore, Floresta, KNN e
SVM) sobre 11 técnicas de balanceamento (10 de reamostragem + nível de
algoritmo com Class Weight e ensembles balanceados), usando o dataset
real de fraudes de cartão de crédito (284.807 transações, 492 fraudes —
desbalanceamento extremo de 1:578).

A métrica analisada é o **recall da classe fraude** — a proporção de
fraudes que o modelo consegue identificar. Em detecção de fraude, deixar
passar uma fraude é muito pior do que investigar um falso alarme, por
isso o recall é a métrica prioritária.

## 1. Ranking dos melhores resultados

| Combinação | Recall |
|---|---|
| NearMiss + Floresta | 0.9324 |
| NearMiss + Árvore | 0.9257 |
| RandomUnderSampler + Logística | 0.9257 |
| NearMiss + Logística | 0.9189 |
| Logística (CW) | 0.9189 |
| RandomUnderSampler + Árvore | 0.9189 |
| EasyEnsemble | 0.9122 |
| BalancedBagging | 0.8986 |
| RandomUnderSampler + Floresta | 0.8986 |
| BalancedRandomForest | 0.8919 |

## 2. Insights por modelo

### Logística — a mais consistente

Varia de 0.84 a 0.93 em quase todas as técnicas. É o modelo que mais se
beneficia do balanceamento e o único que compete de igual para igual com
os ensembles no nível de algoritmo (CW: 0.9189).

### Árvore e Floresta — robustas mesmo sem balanceamento

Recall de ~0.85 já no "Sem balanceamento". Árvores conseguem isolar
regiões da minoria naturalmente, sem precisar de reamostragem. O NearMiss
as leva ao topo (0.93).

### KNN — a mais fraca

Recall de 0.11 a 0.75. Com 30 features, a distância euclidiana perde
significado (maldição da dimensionalidade) e a minoria é esparsa demais
para o KNN encontrar vizinhos próximos. Só o NearMiss a salva (0.75).

### SVM — a mais sensível ao desbalanceamento

Sem balanceamento, recall **0.0000** — prevê tudo como normal. É o modelo
mais afetado pela falta de balanceamento da lista. Mesmo balanceada, não
passa de 0.53 (RandomUnderSampler).

## 3. Insights por técnica

### NearMiss domina

Melhor recall em 3 dos 5 modelos. Mas atenção: ela é **agressiva** (remove
a maioria longe da fronteira), então o recall alto pode vir com precisão
baixa — vale conferir o F1.

### Undersampling > Oversampling neste dataset

RandomUnderSampler supera RandomOverSampler em todos os modelos (ex.:
Floresta 0.8986 vs 0.8581; KNN 0.6824 vs 0.3514). Com desbalanceamento
extremo, remover maioria redundante ajuda mais do que duplicar minoria.

### SMOTE fica no meio do pelotão

E o **KMeansSMOTE é o pior da família** (KNN 0.2095, SVM 0.2230). A lição
da aula se confirma nos dados reais: técnicas sofisticadas sofrem com
minoria escassa.

### SMOTEENN salva o SVM

0.5270 vs 0.2905 do SMOTE puro. A etapa de limpeza remove os exemplos
ambíguos que mais confundiam a SVM.

### Nível de algoritmo é competitivo

EasyEnsemble (0.9122) e Logística (CW) (0.9189) entram no top 5 **sem
tocar nos dados**. Prova prática de que nem sempre é preciso reamostrar.

## 4. Ressalva importante

Esta tabela mostra **apenas o recall**. Com desbalanceamento real de
1:578, recall alto frequentemente custa **muitos falsos positivos**
(precisão baixa). O NearMiss, por exemplo, tende a ter precisão menor que
o SMOTE. Para escolher o modelo final, o **F1** (equilíbrio entre recall
e precisão) é a métrica decisiva — vale rodar o mesmo pivot com
`values='F1'` e `values='Precisão'` para comparar.

## 5. Conclusões da aula

1. **Sem balanceamento, o modelo ignora a fraude** — recall ~0 na SVM e
   ~0.11 no KNN. Acurácia alta (97,6%) esconde um modelo inútil para
   fraude.
2. **Todas as técnicas elevam o recall** — a diferença real aparece na
   precisão e no F1.
3. **Não existe técnica universalmente melhor** — NearMiss domina o
   recall, mas o melhor modelo final depende da métrica de negócio.
4. **Conhecer os dados antes de escolher** — a proporção de 2,4% da
   minoria na amostra exigiu ajustar o KMeansSMOTE
   (`cluster_balance_threshold=0.01`), repetindo a lição da aula.
5. **Nível de algoritmo é uma alternativa real** — Class Weight e
   ensembles balanceados competem com as técnicas de reamostragem sem
   alterar os dados.